server:
  port: 8082

spring:
  application:
    name: member-service

  config:
    import: optional:configserver:http://j9e101.p.ssafy.io:8888

  cloud:
    config:
      name: member
      profile: default

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true

  profiles:
    include: memberdb
