server:
  port: 8082

spring:
  application:
    name: member-service

  config:
    import: optional:configserver:http://j9e101.p.ssafy.io:8888

  cloud:
    config:
      name: member
      profile: default
