server:
  port: 8083

spring:
  data:
    mongodb:
      host: j9e101.p.ssafy.io
      port: 27017
      authentication-database: admin
      database: market
      username: elefante
      password: E1efante1!